# Generated by Django 2.2.16 on 2020-11-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201112_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='slideshow',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='head_portrait',
        ),
    ]
