# Generated by Django 2.2.16 on 2020-11-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201112_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='sort_order',
            new_name='index',
        ),
    ]
